#! /bin/sh

# file      : bootstrap
# author    : Boris Kolpackov <boris@codesynthesis.com>
# copyright : Copyright (c) 2009-2011 Code Synthesis Tools CC
# license   : GNU GPL v2; see accompanying LICENSE file

#
# Bootstrap the automake build system.
#

rm -f config.cache

if test ! -d m4; then
  mkdir m4
fi

autoreconf --install
