#! /bin/sh

# file      : tester
# copyright : Copyright (c) 2009-2013 Code Synthesis Tools CC
# license   : GNU GPL v2; see accompanying LICENSE file

#
# Run an ODB example. The example driver is in the current directory.
# The data files, if any, are in $srcdir.
#

# Globbing returns files in alphabetic order.
#
for f in `echo *.sql`; do
  if test -f $f; then
    $top_builddir/db-driver $f

    if test $? -ne 0; then
      exit 1
    fi
  fi
done

echo ./driver --options-file "$top_builddir/db.options"
./driver --options-file "$top_builddir/db.options"
