/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */


IF OBJECT_ID('person', 'U') IS NOT NULL
  DROP TABLE [person];
GO


CREATE TABLE [person] (
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
  [num] INT NOT NULL UNIQUE,
  [str] VARCHAR(max) NOT NULL);
GO
